name: Notify new events

on:
  workflow_dispatch: # 手動実行を可能にするトリガー

jobs:
  notify_new_events:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for committing and pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # 必要なPythonのバージョンを指定

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run scraping and notify
        run: uv run python app/run.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
          WEB_PAGE_URL: ${{ secrets.WEB_PAGE_URL }}

      - name: Pull main branch
        run: |
          git fetch origin
          git checkout main
          git pull

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add app/sent_events.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Event Cache"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
